### ISSUE TITLE
object 'unique.arcs' not found error in skeleton.R 

### ISSUE THREAD

**Issue by shahashka** [jirehhuang/phsl#1]
Hello,

I am trying to use your code following the man/phgs.Rd example (child network from the bnlearn repository). I'm running into the following error when I try to run: 

```
bn1 <- phgs(x = x, maximize = "hc", 
+             maximize.args = list(maxp = 8, restart = 10, perturb = 10),
+             alpha = 1e-2, max.sx = 3, maxp = 8, path = 10,
+             min_alpha = 1e-5, sort_pval = TRUE, max_groups = 20, 
+             debug = TRUE)
ℹ bnsl:             structure learning with restrict = ppc, path = 10, hgi = TRUE, maximize = hc
Error in skeleton(cluster = NULL, test = "mi", alpha = 0.01, max.sx = 3,  : 
  object 'unique.arcs' not found
```
Please let me know if this is fixable. Thank you!

**Comment by jirehhuang** [comment]
Thank you for raising the issue!

This package was built with a previous version of bnlearn (4.7, iirc). It seems that [the hidden function `bnlearn:::unique.arcs()` was renamed to `bnlearn:::arcs.unique()` in `bnlearn` 4.8.3](https://github.com/cran/bnlearn/commit/dda6458daf2e0b25d3e87313f35f23d8a1c440c1), among other changes that affect the phsl package. 

For the time being, before I am able to catch up phsl to the bnlearn updates, I recommend installing [a previous version of bnlearn such as 4.8.1](https://cran.r-project.org/src/contrib/Archive/bnlearn/), which should solve the issue.

**Comment by shahashka** [comment]
Thank you for the response. I installed bnlearn 4.8.1, but am still getting the same error:
```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] phsl_1.0       bnlearn_4.8.1  devtools_2.4.5 usethis_2.1.6 
> bn1 <- phgs(x = x, maximize = "hc", 
+             maximize.args = list(maxp = 8, restart = 10, perturb = 10),
+             alpha = 1e-2, max.sx = 3, maxp = 8, path = 10,
+             min_alpha = 1e-5, sort_pval = TRUE, max_groups = 20, 
+             debug = TRUE)
ℹ bnsl:             structure learning with restrict = ppc, path = 10, hgi = TRUE, maximize = hc
Error in skeleton(cluster = NULL, test = "mi", alpha = 0.01, max.sx = 3,  : 
  object 'unique.arcs' not found
```
Let me know if you have any other ideas, thanks again!

**Comment by shahashka** [comment]
Restarting R fixed this, thanks!

**Comment by jirehhuang** [comment]
Reopening because this issue persists.
